spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog
    username: catalog
    password: catalog
  flyway:
    user: catalog
    password: catalog
    schemas:
      - public
      - catalog

server:
  port: 8081
  servlet:
    context-path: /api